site_name: Nexus Unit Testing Documentation
site_url: https://thenexusavenger.github.io/Nexus-Unit-Testing
repo_name: TheNexusAvenger/Nexus-Unit-Testing
repo_url: https://github.com/TheNexusAvenger/Nexus-Unit-Testing

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Getting Started: 
    - Writing Tests: getting-started/writing-tests.md
    - Running Tests: getting-started/running-tests.md
    - Classes:
      - UnitTest: getting-started/classes/UnitTest.md
      - ErrorAssertor: getting-started/classes/ErrorAssertor.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite